version: '3.8'

services:
  gol-db:
    image: mysql:8
    volumes:
      - gol-db-volume:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: qwertyuiop0987654321
      MYSQL_DATABASE: gol
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwertyuiop0987654321
    networks:
      - gol-backend

  gol-spring:
    image: ghcr.io/yangsijun528/gol:0.0.1
    platform: linux/arm64 # to arm64 when use OS in x86
    depends_on:
      - gol-db   # db 컨테이너가 생성될 때 까지 대기
    ports:
      - "80:8080"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      GAUTH_REDIRECT_URI: http://localhost:3000/gauth/code
      AUTH_REDIRECT_URI: http://localhost:3000/
      MYSQL_HOST: jdbc:mysql://gol-db:3306/gol?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: qwertyuiop0987654321
      JOB_ENABLED: false
      DDL_AUTO: validate
      JOB_NAME:
      RIOT_API_KEY: RGAPI-04db374f-a866-43b7-8f51-7421418f1a08
    networks:
      - gol-backend

volumes:
  gol-db-volume: {}

networks:
  gol-backend: {}

