server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        check_nullability: true
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  profiles:
    include: auth