server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
      name: ${job.name:NONE}
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

gauth:
  client-id: e5502aa30a504963a3327e84b916e1bff3eafe1987834bfd9806a01bf8c2a8cd
  client-secret: a8edd1197b894dffac591c722d6b43c5e871bee0b9274e82b5bb997e40df5b4e
  redirect-uri: http://localhost:3000/gauth/code

jwt:
  secret-key: 6250655368566D5971337436763979244226452948404D635166546A576E5A72
  access-expiration: 86400000
  refresh-expiration: 604800000
  issuer: example.com
