name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ "renew-1" ]
  pull_request:
    branches: [ "renew-1" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Gradls's permission
        run : chmod +x gradlew 

      - name: Create application.yml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_CI }}" > ./src/main/resources/application.yml

      - name: Run build with Gradle wrapper
        run: ./gradlew clean build
