name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ "renew-1" ]
  pull_request:
    branches: [ "renew-1" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Check secrets
        run: |
          echo "${{ secrets.TEST }}" | sed 's/./& /g'
        shell: bash

      - name: Check secrets.APPLICATION_CI 
        run: |
          echo "${{ secrets.APPLICATION_CI }}" | sed 's/./& /g'
        shell: bash

      - name: Create application.yml
        run: |
          rm ./src/main/resources/application.yml
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_CI }}" > ./src/main/resources/application.yml
        shell: bash
        
      - name: Run build with Gradle wrapper
        run: ./gradlew clean build
